import os
import sys
import json
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import derma_probe as DP
import c1_replication_probe as C1

COVS = C1.COVS
FLAGS = C1.FLAGS
N_SEEDS = C1.N_SEEDS
N_RAND = C1.N_RAND
OUT_JSON = os.environ.get("C1O_OUT", "c1_orthogonal_probe.json")
REP_JSON = os.environ.get("C1_OUT", "c1_replication_probe.json")


def aurc_misclass(f, correct):
    return C1.auc([1.0 - float(correct[f <= np.percentile(f, c * 100)].mean())
                   for c in COVS])


def build_cifar100_labeled(rng, n_ref=400):
    cd = DP.CFG["cache_dir"]

    def p(k, s):
        return os.path.join(cd, f"dino_{k}_{s}.npy")
    ftr, ytr = np.load(p("feat", "train")).astype(float), np.load(p("lab", "train"))
    fte, yte = np.load(p("feat", "test")).astype(float), np.load(p("lab", "test"))
    held, hout = list(range(50)), list(range(50, 100))
    refs = []
    for c in held:
        X = ftr[ytr == c]
        if len(X) > n_ref:
            X = X[rng.choice(len(X), n_ref, replace=False)]
        refs.append(X)

    def sub(x, n):
        return x if len(x) <= n else x[rng.choice(len(x), n, replace=False)]

    m_in = np.where(np.isin(yte, held))[0]
    if len(m_in) > 800:
        m_in = rng.choice(m_in, 800, replace=False)
    groups = {"in": fte[m_in], "near": sub(fte[np.isin(yte, hout)], 800)}
    for s in ["svhn", "dtd_lr32", "lsun", "isun", "places365_lr32", "cifar10"]:
        f = os.path.join(cd, f"dino_feat_far_{s}.npy")
        if os.path.exists(f):
            groups[s] = sub(np.load(f).astype(float), 800)
    return groups, refs, yte[m_in], held


def one_seed(seed):
    rng = np.random.default_rng(seed)
    groups, refs, y_in, held = build_cifar100_labeled(rng)
    Q = np.vstack([groups[g] for g in groups])
    S = DP.Space(Q, refs, dict(DP.CFG))
    M = dict(S.metrics())

    n_in = len(y_in)
    assert np.array_equal(Q[:n_in], groups["in"]), "in-group 이 Q 의 선두가 아니다"

    cls2i = {c: i for i, c in enumerate(held)}
    pred = S.probe.predict(groups["in"])
    yi = np.array([cls2i[int(c)] for c in y_in])
    correct = (pred == yi)

    mis = {fn: aurc_misclass(M[fn][:n_in], correct) for fn in FLAGS}
    rand = [aurc_misclass(rng.random(n_in), correct) for _ in range(N_RAND)]
    return dict(seed=seed, n_in=int(n_in), n_q=int(len(Q)), C=len(refs),
                probe_acc=float(correct.mean()),
                aurc_misclass=mis,
                aurc_misclass_random=float(np.mean(rand)),
                aurc_misclass_random_draws=[float(v) for v in rand],
                aurc_misclass_random_analytic=float(0.5 * (1.0 - correct.mean())))


def summarize(rows):
    print("\n" + "=" * 78, file=sys.stderr)
    print(f"[CIFAR-100 misclass]  seeds={len(rows)}  n_in={rows[0]['n_in']}", file=sys.stderr)
    print("=" * 78, file=sys.stderr)
    acc = np.array([r["probe_acc"] for r in rows])
    print(f"  probe accuracy  mean={acc.mean():.4f}  sd={acc.std(ddof=1):.4f}", file=sys.stderr)
    print(f"  {'score':>9} {'mean':>9} {'sd':>8} {'min':>9} {'max':>9}", file=sys.stderr)
    out = {}
    for fn in FLAGS:
        v = np.array([r["aurc_misclass"][fn] for r in rows])
        print(f"  {fn:>9} {v.mean():9.4f} {v.std(ddof=1):8.4f} "
              f"{v.min():9.4f} {v.max():9.4f}", file=sys.stderr)
        out[fn] = dict(mean=float(v.mean()), sd=float(v.std(ddof=1)),
                       n=len(v), per_seed=[float(x) for x in v])
    lvl = np.array([r["aurc_misclass_random"] for r in rows])
    ana = np.array([r["aurc_misclass_random_analytic"] for r in rows])
    print(f"  {'random':>9} {lvl.mean():9.4f} {lvl.std(ddof=1):8.4f} "
          f"{lvl.min():9.4f} {lvl.max():9.4f}   (0.5*err = {ana.mean():.4f})", file=sys.stderr)
    return dict(tag="CIFAR-100 misclass  n_ref=400",
                probe_acc_mean=float(acc.mean()), probe_acc_sd=float(acc.std(ddof=1)),
                misclass=out,
                misclass_level_mean=float(lvl.mean()),
                misclass_level_sd=float(lvl.std(ddof=1)),
                misclass_level_analytic=float(ana.mean()),
                rows=rows)


TT = {"knn_std": r"\texttt{knn\_std}", "lid": r"\texttt{lid}",
      "energy": r"\texttt{energy}", "msp": r"\texttt{msp}",
      "maha": r"\texttt{maha}"}


def emit_orthogonal(O, R):
    inst = {fn: float(np.mean([r["aurc"][fn] for r in R["cifar100"]["rows"]]))
            for fn in FLAGS}
    inst["random"] = R["cifar100"]["level_mean"]
    mis = {fn: O["misclass"][fn]["mean"] for fn in FLAGS}
    mis["random"] = O["misclass_level_mean"]

    best_i = min(FLAGS, key=lambda k: inst[k])
    best_m = min(FLAGS, key=lambda k: mis[k])
    order = sorted(FLAGS + ["random"], key=lambda k: inst[k])

    def cell(fn, d, best):
        return (r"$\mathbf{%.4f}$" if fn == best else r"$%.4f$") % d[fn]

    print(r"% ---- generated by c1_orthogonal_probe.py — do not edit by hand ----")
    print(r"\begin{tabular}{lrr}")
    print(r"\toprule")
    print(r"Score & AURC (instab.) & AURC (misclass.) \\")
    print(r"\midrule")
    for fn in order:
        if fn == "random":
            print(r"\textit{random}   & \textit{%.4f} & \textit{%.4f} \\"
                  % (inst["random"], mis["random"]))
        else:
            print(r"%s & %s & %s \\"
                  % (TT[fn].ljust(17), cell(fn, inst, best_i), cell(fn, mis, best_m)))
    print(r"\bottomrule")
    print(r"\end{tabular}")


def checks(O, R):
    out = sys.stderr
    ok = True

    def say(c, msg):
        nonlocal ok
        ok &= c
        print(("  [ok]   " if c else "  [FAIL] ") + msg, file=out)

    print("\n" + "=" * 74, file=out)
    print("정합성 검사", file=out)
    print("=" * 74, file=out)

    s_o = [r["seed"] for r in O["rows"]]
    s_r = [r["seed"] for r in R["cifar100"]["rows"]]
    say(s_o == s_r, f"시드 집합 일치: {s_o} == {s_r}")
    say(all(a["n_q"] == b["n_q"] for a, b in zip(O["rows"], R["cifar100"]["rows"])),
        "시드별 질의 수(n_q)가 tab:worse 의 run 과 일치")

    try:
        S6 = json.load(open("sec6_values.json"))["cifar100"]
    except (OSError, ValueError, KeyError):
        S6 = None
    if S6 is None:
        print("  [skip] sec6_values.json 없음 — seed 0 재현 검사 생략", file=out)
    else:
        print(file=out)
        print("  seed 0 재현 (sec6_values.json = 논문 현재 1-run 값):", file=out)
        r0 = O["rows"][0]
        for fn in FLAGS:
            a, b = r0["aurc_misclass"][fn], S6["aurc_misclass"][fn]
            say(abs(a - b) < 1e-9, f"misclass/{fn}: {a:.6f} vs {b:.6f}")
        a, b = r0["probe_acc"], S6["probe_acc"]
        say(abs(a - b) < 1e-9, f"probe_acc: {a:.4f} vs {b:.4f}")
        r0i = R["cifar100"]["rows"][0]["aurc"]
        for fn in FLAGS:
            a, b = r0i[fn], S6["table"][fn]["aurc"]
            say(abs(a - b) < 1e-9, f"instab/{fn}:   {a:.6f} vs {b:.6f}")

    print(file=out)
    a, p = O["misclass_level_mean"], O["misclass_level_analytic"]
    say(abs(a - p) < 5e-4,
        f"AURC_rand(misclass)={a:.4f} vs 0.5*(1-acc)={p:.4f}  (항등식)")

    inst = {fn: float(np.mean([r["aurc"][fn] for r in R["cifar100"]["rows"]]))
            for fn in FLAGS}
    inst["random"] = R["cifar100"]["level_mean"]
    mis = {fn: O["misclass"][fn]["mean"] for fn in FLAGS}
    mis["random"] = O["misclass_level_mean"]
    print(file=out)
    print("  본문 주장 (app:orthogonal):", file=out)
    say(min(FLAGS, key=lambda k: inst[k]) == "knn_std",
        f"knn_std 가 instability 열 최상  ({inst['knn_std']:.4f})")
    say(max(FLAGS, key=lambda k: mis[k]) == "knn_std",
        f"knn_std 가 misclass 열 최하    ({mis['knn_std']:.4f})")
    say(min(FLAGS, key=lambda k: mis[k]) == "msp",
        f"msp 가 misclass 열 최상        ({mis['msp']:.4f})")
    say(sorted(FLAGS, key=lambda k: inst[k])[-2] == "msp",
        f"msp 가 instability 열 뒤에서 둘째 ({inst['msp']:.4f})")
    worse_i = [f for f in FLAGS if inst[f] > inst["random"]]
    worse_m = [f for f in FLAGS if mis[f] > mis["random"]]
    say(set(worse_i) == {"energy", "msp", "maha"},
        f"instability 에서 coin flip 에 지는 점수: {sorted(worse_i)}")
    say(set(worse_m) == {"knn_std", "lid"},
        f"misclass 에서 coin flip 에 지는 점수:   {sorted(worse_m)}")
    say(set(worse_i) | set(worse_m) == set(FLAGS)
        and not (set(worse_i) & set(worse_m)),
        "각 점수는 설계되지 않은 열에서 정확히 한 번씩 coin flip 에 진다")

    print(file=out)
    print("  결과: " + ("모든 검사 통과" if ok else "** 실패한 검사 있음 **"), file=out)
    return ok


def main():
    R = json.load(open(REP_JSON))

    if "--table" in sys.argv:
        O = json.load(open(OUT_JSON))
    else:
        rows = []
        for s in range(N_SEEDS):
            t0 = time.time()
            rows.append(one_seed(s))
            r = rows[-1]
            print(f"  [cifar seed {s}] acc={r['probe_acc']:.4f} "
                  f"msp={r['aurc_misclass']['msp']:.4f} "
                  f"knn_std={r['aurc_misclass']['knn_std']:.4f}  "
                  f"({time.time()-t0:.0f}s)", file=sys.stderr, flush=True)
        O = summarize(rows)
        json.dump(O, open(OUT_JSON, "w"), indent=2, default=float)
        print(f"\n[saved] {OUT_JSON}", file=sys.stderr)

    emit_orthogonal(O, R)
    sys.exit(0 if checks(O, R) else 1)


if __name__ == "__main__":
    main()
