import json
import sys
import numpy as np

J = json.load(open("c1_replication_probe.json"))
ORDER = ["knn_std", "lid", "energy", "msp", "maha"]
TT = {"knn_std": r"\texttt{knn\_std}", "lid": r"\texttt{lid}",
      "energy": r"\texttt{energy}", "msp": r"\texttt{msp}",
      "maha": r"\texttt{maha}"}
DS = [("cifar100", r"\textit{CIFAR-100} ($C{=}50$)"),
      ("derma", r"\textit{DermaMNIST} ($C{=}3$)")]


def g(ds, fn):
    return J[ds]["gaps"][fn]


def rho(ds, fn):
    return J[ds]["rho"][fn]


def aurc_mean(ds, fn):
    return float(np.mean([r["aurc"][fn] for r in J[ds]["rows"]]))


def emit_worse():
    print(r"% ---- generated by c1_tables.py — do not edit by hand ----")
    print(r"\begin{tabular}{l rrl c rrl}")
    print(r"\toprule")
    print(r"& \multicolumn{3}{c}{%s} && \multicolumn{3}{c}{%s} \\" % (DS[0][1], DS[1][1]))
    print(r"\cmidrule(lr){2-4}\cmidrule(lr){6-8}")
    print(r"Score & $\rho(M,\widehat{T})$ & AURC & $\Delta$ (\%) "
          r"&& $\rho(M,\widehat{T})$ & AURC & $\Delta$ (\%) \\")
    print(r"\midrule")
    for fn in ORDER:
        cells = []
        for ds, _ in DS:
            v, r_ = g(ds, fn), rho(ds, fn)
            half = 0.5 * (v["ci"][1] - v["ci"][0])
            d = "%+.2f" % v["mean"]
            if v["mean"] > 0:
                d = r"$\mathbf{%s}$" % d
            else:
                d = "$%s$" % d
            cells.append(r"$%+.3f$ & %.4f & %s{\scriptsize$\,\pm%.2f$}"
                         % (r_["That_mean"], aurc_mean(ds, fn), d, half))
        print(r"%s & %s && %s \\" % (TT[fn], cells[0], cells[1]))
    print(r"\midrule")
    rc = []
    for ds, _ in DS:
        rc.append(r"\textit{$%+.3f$} & \textit{%.4f} & \textit{---}"
                  % (np.mean([r["rho_That"].get("random", 0.0) for r in J[ds]["rows"]])
                     if "random" in J[ds]["rows"][0]["rho_That"] else 0.0,
                     J[ds]["level_mean"]))
    print(r"\textit{random} & %s && %s \\" % (rc[0], rc[1]))
    print(r"\bottomrule")
    print(r"\end{tabular}")


def emit_seeds():
    print()
    print(r"% ---- generated by c1_tables.py ----")
    print(r"\begin{tabular}{l rrrr c rrrr}")
    print(r"\toprule")
    print(r"& \multicolumn{4}{c}{\textit{CIFAR-100}} && \multicolumn{4}{c}{\textit{DermaMNIST}} \\")
    print(r"\cmidrule(lr){2-5}\cmidrule(lr){7-10}")
    print(r"Score & mean & sd & range & sign && mean & sd & range & sign \\")
    print(r"\midrule")
    for fn in ORDER:
        cells = []
        for ds, _ in DS:
            v = g(ds, fn)
            p = v["per_seed"]
            cells.append(r"$%+.2f$ & $%.2f$ & {\scriptsize$[%+.2f,%+.2f]$} & $%d/%d$"
                         % (v["mean"], v["sd"], min(p), max(p),
                            v["sign_agree"], v["n"]))
        print(r"%s & %s && %s \\" % (TT[fn], cells[0], cells[1]))
    print(r"\bottomrule")
    print(r"\end{tabular}")


def emit_level():
    print()
    print(r"% ---- generated by c1_tables.py ----")
    print(r"\begin{tabular}{lcc}")
    print(r"\toprule")
    print(r" & \textit{CIFAR-100} & \textit{DermaMNIST} \\")
    print(r"\midrule")
    rowdefs = [
        (r"Baseline area $\mathrm{AURC}_{\mathrm{rand}}$",
         lambda d: "%.4f" % J[d]["level_mean"]),
        (r"Predicted $\tfrac{1}{2}\overline{T}$",
         lambda d: "%.4f" % J[d]["level_analytic"]),
        (r"Level spread across seeds",
         lambda d: "%.2f\\%%" % (100 * (max(r["aurc_random"] for r in J[d]["rows"])
                                        / min(r["aurc_random"] for r in J[d]["rows"]) - 1))),
        (r"Widest interval on $\Delta$",
         lambda d: "%.2f\\,pp" % max(g(d, f)["ci"][1] - g(d, f)["ci"][0] for f in ORDER)),
        (r"$\mathrm{corr}(\mathrm{AURC}_M, \mathrm{AURC}_{\mathrm{rand}})$",
         lambda d: "%.2f--%.2f" % tuple(_corr_range(d))),
    ]
    for lab, f in rowdefs:
        print(r"%s & %s & %s \\" % (lab, f("cifar100"), f("derma")))
    print(r"\bottomrule")
    print(r"\end{tabular}")


def _corr_range(ds):
    lvl = np.array([r["aurc_random"] for r in J[ds]["rows"]])
    cs = [np.corrcoef(np.array([r["aurc"][f] for r in J[ds]["rows"]]), lvl)[0, 1]
          for f in ORDER]
    return min(cs), max(cs)


PAPER_OLD = {
    "cifar100": dict(knn_std=0.1199, lid=0.1216, energy=0.1307, msp=0.1312,
                     maha=0.1336, random=0.1283),
    "derma": dict(knn_std=0.0484, lid=0.0485, energy=0.0522, msp=0.0562,
                  maha=0.0694, random=0.0609),
}
SWEEP400 = dict(knn_std=0.1209, lid=0.1227, energy=0.1327, msp=0.1329,
                maha=0.1348, random=0.1297)


def checks():
    out = sys.stderr
    ok = True

    def say(c, msg):
        nonlocal ok
        ok &= c
        print(("  [ok]   " if c else "  [FAIL] ") + msg, file=out)

    print("\n" + "=" * 74, file=out)
    print("정합성 검사", file=out)
    print("=" * 74, file=out)

    for ds, _ in DS:
        a, p = J[ds]["level_mean"], J[ds]["level_analytic"]
        say(abs(a - p) < 5e-4,
            f"{ds}: AURC_rand={a:.4f} vs 0.5*meanT={p:.4f}  (항등식)")

    print(file=out)
    for ds, _ in DS:
        for fn in ORDER:
            v = g(ds, fn)
            say(np.sign(v["ci"][0]) == np.sign(v["ci"][1]),
                f"{ds}/{fn}: 95% CI [{v['ci'][0]:+.2f},{v['ci'][1]:+.2f}] 이 0 을 제외")

    print(file=out)
    for ds, _ in DS:
        for fn in ORDER:
            r_ = rho(ds, fn)
            say(r_["That_sign"] == r_["n"],
                f"{ds}/{fn}: rho(M,That) 부호가 {r_['That_sign']}/{r_['n']} 시드에서 일정 "
                f"({r_['That_mean']:+.3f}+-{r_['That_sd']:.3f})")
            say(r_["rule_agree"] == r_["n"],
                f"{ds}/{fn}: eq:rule (sign rho(M,That)==sign rho(M,T)) "
                f"{r_['rule_agree']}/{r_['n']}")

    print("  이전 판(1 run)과의 대조 — 판정 아님, 기록:", file=out)
    for ds, _ in DS:
        for fn in ORDER:
            v = g(ds, fn)
            old = 100 * (PAPER_OLD[ds][fn] / PAPER_OLD[ds]["random"] - 1)
            z = (old - v["mean"]) / v["sd"]
            print(f"    {ds:>8}/{fn:<8} 이전 {old:+7.2f}%  신규 {v['mean']:+7.2f}%"
                  f"  ({z:+.1f} sd)", file=out)

    print(file=out)
    print("  tab:sweep caption 의 재현 주장 (sweep@400 vs 새 tab:worse):", file=out)
    worst = 0.0
    for fn in ORDER:
        a = 100 * (SWEEP400[fn] / SWEEP400["random"] - 1)
        b = g("cifar100", fn)["mean"]
        worst = max(worst, abs(a - b))
        say(a * b > 0, f"{fn}: sweep@400 {a:+.2f}%  tab:worse {b:+.2f}%  "
                       f"차이 {abs(a-b):.2f}pp  부호 일치")
    say(worst <= 0.21 + 5e-3, f"최대 차이 {worst:.2f}pp  (caption 이 주장하는 값)")
    lvl = 100 * (SWEEP400["random"] / J["cifar100"]["level_mean"] - 1)
    say(abs(abs(lvl) - 0.43) < 5e-3, f"기준선 level 차이 {lvl:+.2f}%  (caption: 0.43%)")

    print(file=out)
    print("  §6.2 순서 주장:", file=out)
    RHO_ORDER = ["knn_std", "lid", "energy", "msp", "maha"]
    narrow = None
    for ds, _ in DS:
        rs = sorted(RHO_ORDER, key=lambda k: -rho(ds, k)["That_mean"])
        ds_ = sorted(RHO_ORDER, key=lambda k: g(ds, k)["mean"])
        say(rs == ds_, f"{ds}: rho 순서 == Delta 순서  ({' > '.join(rs)})")
        for a, b in zip(ds_[:-1], ds_[1:]):
            d = np.array(g(ds, b)["per_seed"]) - np.array(g(ds, a)["per_seed"])
            se = d.std(ddof=1) / np.sqrt(len(d))
            lo = d.mean() - 1.96 * se
            if narrow is None or d.mean() < narrow[0]:
                narrow = (d.mean(), ds, a, b, lo)
    say(abs(narrow[0] - 0.02) < 5e-3 and narrow[1] == "derma"
        and set(narrow[2:4]) == {"knn_std", "lid"} and narrow[4] < 0,
        f"가장 좁은 인접 쌍 = {narrow[1]}/{narrow[2]}-{narrow[3]} {narrow[0]:+.2f}pp, "
        f"CI 하한 {narrow[4]:+.2f} (0 을 가로지름)  — 본문 주장과 일치")

    print(file=out)
    print("  결과: " + ("모든 검사 통과" if ok else "** 실패한 검사 있음 **"), file=out)
    return ok


if __name__ == "__main__":
    emit_worse()
    emit_seeds()
    emit_level()
    sys.exit(0 if checks() else 1)
